config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "fridges#index"
  resources :fridges, only: [:index, :create] do
    resources :shoppings, only: [:index, :create]
  end
  resources :items, only: [:create, :update, :destroy]
  resources :requests, only: [:create, :update, :destroy]
  resources :losses, only: :create
end

app/models/amount.rb
class Amount < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'なし' },
    { id: 2, name: '残りわずか' },
    { id: 3, name: '半分程度' },
    { id: 4, name: 'たくさん' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '生鮮食品' },
    { id: 2, name: '野菜・果物' },
    { id: 3, name: '調味料' },
    { id: 4, name: '飲料' },
    { id: 5, name: '日用品' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/fridge.rb
class Fridge < ApplicationRecord
  has_many :users
  has_many :items
  has_many :requests
  has_many :shoppings
  has_many :losses
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :amount
  belongs_to :fridge
  has_many :shopping_items, dependent: :destroy
  has_many :shoppings, through: :shopping_items
  has_many :losses

  # validate :exp_date_check #今は必要かわからないのでコメントアウト 2022/02/17

  with_options presence: true do
    validates :regular
    validates :name
  end

  with_options numericality: { other_than: 0, message: 'を選択してください' } do
    validates :category_id
    validates :amount_id
  end

  def latest_shopping_date
    shoppings.order(created_at: :desc).first.shopping_date
  end

  private

  def exp_date_check
    errors.add(:exp_date, 'は今日以降を選択してください') if exp_date.present? && exp_date < Date.today
  end
end

app/models/loss.rb
class Loss < ApplicationRecord
  belongs_to :fridge
  belongs_to :item
end

app/models/loss_item.rb
class LossItem
  include ActiveModel::Model
  attr_accessor :loss_date, :fridge_id, :item_id, :amount_id, :category_id

  with_options presence: true do
    validates :loss_date
    validates :fridge_id
    validates :item_id
    validates :amount_id, numericality: { other_than: 1, message: 'is nothing' }
    validates :category_id, numericality: { other_than: 5, message: "is can't be loss" }
  end

  def save
    Loss.create(loss_date: loss_date, fridge_id: fridge_id, item_id: item_id)
    item = Item.find(item_id)
    item.update(amount_id: 1, exp_date: nil)
  end
end

app/models/loss_items.rb
class LossItems
  include ActiveModel::Model
  attr_accessor :loss_date, :fridge_id, :item_id, :amount_id

  with_options presence: true do
    validates :loss_date
    validates :fridge_id
    validates :item_id
    validates :amount_id, numericality: { other_than: 1, message: "is nothing" }
  end

  def save
    Loss.create(loss_date: loss_date, fridge_id: fridge_id, item_id: item_id)
    item = Item.find(item_id)
    item.update(amount_id: 1, exp_date: nil)
  end

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :fridge
  belongs_to :user

  with_options presence: true do
    validates :fridge_id
    validates :user_id
  end
end

app/models/shopping.rb
class Shopping < ApplicationRecord
  belongs_to :fridge
  belongs_to :user
  has_many :shopping_items
  has_many :items, through: :shopping_items
end

app/models/shopping_form.rb
class ShoppingForm
  include ActiveModel::Model
  attr_accessor :shopping_date, :fridge_id, :user_id, :shopping_item_ids

  with_options presence: true do
    validates :shopping_date
    validates :fridge_id
    validates :user_id
    validates :shopping_item_ids
  end

  def save
    ids = shopping_item_ids
    Shopping.create(shopping_date: shopping_date, fridge_id: fridge_id, user_id: user_id, item_ids: ids)
    Item.where(id: ids).update_all(amount_id: 4, exp_date: nil)
  end
end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord
  belongs_to :shopping
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :fridge, optional: true
  has_one :request

  with_options presence: true do
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数を両方含む必要があります' }, on: :create
    validates :password_confirmation, on: :create
    validates :nickname, uniqueness: { case_sensitive: true }
    validates :gender
    validates :birthday
  end
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
  def index
    @fridge = Fridge.new
    @item = Item.new
    @request = Request.new
    @q = Item.ransack(params[:q])
    @q.sorts = ['amount_id desc', 'category_id asc', 'exp_date asc', 'regular desc']
    # 残量：少ない→多い カテゴリ：生鮮→日用品 賞味期限：昇順 常備アイテム：チェックが優先
    @items = @q.result(distinct: true)
  end

  def create
    @fridge = Fridge.new(fridge_params)
    @user = User.find(current_user.id)
    if @fridge.save
      @user.update(fridge_id: @fridge.id)
      redirect_to root_path, success: '冷蔵庫を作成しました'
    else
      render :index
    end
  end

  private

  def fridge_params
    params.require(:fridge).permit(:title)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:update, :destroy]
  before_action :same_fridge?, only: [:update, :destroy]

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, success: 'アイテムを登録しました'
    else
      redirect_to root_path, danger: "アイテムの登録に失敗しました：<br>#{@item.errors.full_messages.join(',')}"
    end
  end

  def update
    if @item.update(item_params)
      redirect_to root_path, success: 'アイテムを更新しました'
    else
      redirect_to root_path, danger: "アイテムの更新に失敗しました：<br>#{@item.errors.full_messages.join(',')}"
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path, success: 'アイテムを削除しました'
  end

  private

  def item_params
    params.require(:item).permit(:regular, :name, :category_id, :amount_id, :exp_date).merge(fridge_id: current_user.fridge_id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def same_fridge?
    # アイテムに紐づく冷蔵庫IDとユーザーの冷蔵庫IDが一致しなければリダイレクトする
    redirect_to root_path unless @item.fridge_id == current_user.fridge_id
  end
end

app/controllers/losses_controller.rb
class LossesController < ApplicationController
  before_action :authenticate_user!

  def create
    @loss_item = LossItem.new(loss_params)
    if @loss_item.valid?
      @loss_item.save
      redirect_to root_path, danger: 'アイテムをロスにしました'
    else
      redirect_to root_path
    end
  end

  private

  def loss_params
    params.permit(:loss_date, :fridge_id, :item_id, :amount_id, :category_id)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_request, only: [:update, :destroy]
  before_action :same_fridge?, only: [:update, :destroy]

  def create
    @request = Request.new(request_params)
    if @request.save
      redirect_to root_path, success: '共有リクエストを申請しました'
    else
      render_top
    end
  end

  def update
    if @request.user.update(fridge_id: @request.fridge_id)
      @request.destroy
      redirect_to root_path, success: '共有リクエストを承認しました'
    else
      render_top
    end
  end

  def destroy
    @request.destroy
    redirect_to root_path, danger: '共有リクエストを拒否しました'
  end

  private

  def request_params
    params.require(:request).permit(:fridge_id, :user_id)
  end

  def set_request
    @request = Request.find(params[:id])
  end

  def render_top
    @q = Item.ransack(params[:q])
    @q.sorts = ['regular desc', 'amount_id asc', 'exp_date asc']
    # 優先順位：常備アイテム、残量、賞味/消費期限順
    @items = @q.result(distinct: true)
    render template: 'fridges/index'
  end

  def same_fridge?
    # 共有リクエストを同じ冷蔵庫のユーザー以外が操作するとリダイレクトされる処理
    unless @request.fridge_id == current_user.fridge_id || @request.fridge_id == current_user.request.fridge_id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fridges_helper.rb
module FridgesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/losses_helper.rb
module LossesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/fridges/_item.html.erb
<tbody>
  <% if current_user.fridge_id == item.fridge_id %>
    <%= form_with model: item, local: true do |f| %>
      <tr>
        <td><%= f.check_box :regular, {class: "form-check-input", type: "checkbox", id: "checkboxNoLabel" }, "1", "0" %></td>
        <td><%= f.text_field :name, placeholder: "アイテム名を入力してください", class: 'form-control' %></td>
        <td><%= f.collection_select(:amount_id, Amount.where.not(id: 0), :id, :name, {}, {class:"form-control"}) %></td>
        <td><%= f.collection_select(:category_id, Category.where.not(id: 0), :id, :name, {}, {class:"form-control"}) %></td>
        <td><%= f.date_field :exp_date, class: 'form-control'%></td>
        <td class="fw-bold"><%= item.latest_shopping_date if item.shoppings.present? %></td>
        <td><%= f.submit "更新", class: 'btn btn-warning' %></td>
        <td><%= link_to "ロス", losses_path(loss_date: Date.today, fridge_id: item.fridge_id, item_id: item.id, amount_id: item.amount.id, category_id: item.category.id), method: :post, class: 'btn btn-danger' unless item.category_id == 5 || item.amount_id == 1 %></td>
        <td><%= link_to "削除", item_path(item.id), method: :delete, data: { confirm: "#{item.name}を本当に削除してもよろしいですか？" }, class: 'btn btn-secondary' %></td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/fridges/index.html.erb
<%= render "shared/header"%>
<div class="box">
  <%# フラッシュメッセージ %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <% message2 = message.gsub(",","<br>") %> <%# 複数のメッセージがある場合に改行する処理 %>
      <%= message2.html_safe %>
    </div>
  <% end %>

  <%# 冷蔵庫新規登録＆共有リクエストフォーム %>
  <div class= "container">
    <div class= "row">
      <% if user_signed_in? && current_user.fridge_id.nil? && current_user.request.nil? %>
        <div class="lead mt-5">冷蔵庫を新規作成してください。共有する場合はその冷蔵庫IDを入力して共有リクエストを送信してください</div>
          <%= form_with model: @fridge, local: true do |f| %>
            <div class='col-6 mx-auto mt-3'>
              <%= f.text_field :title, placeholder: "【冷蔵庫新規作成】冷蔵庫の名前を入力してください", class: 'form-control' %>
              <%= f.submit "新規作成", class: 'btn btn-primary' %>
            </div>
          <% end %>
          <%= form_with model: @request, local: true do |f| %>
            <div class='col-6 mx-auto mt-5'>
              <%= f.number_field :fridge_id, placeholder: "【冷蔵庫共有】共有したい冷蔵庫IDを入力してください", class: 'form-control' %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.submit "共有リクエスト", class: 'btn btn-success' %>
              <%= render 'shared/error_messages', model: f.object %>
            </div>
          <% end %>
      <% elsif user_signed_in? && current_user.request.present? %>
        <h3 class="mt-5"><%= "現在、冷蔵庫ID: #{current_user.request.fridge_id}の共有リクエストを申請中です" %></h3>
        <div class='col mx-auto mt-1'>
          <%= button_to "申請を取り消す", request_path(current_user.request.id), method: :delete, class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>


  <%# 冷蔵庫情報 %>
  <div class= "container">
    <div class= "row">
      <%# 冷蔵庫名表示 %>  
      <% if user_signed_in? && current_user.fridge_id.present? %>
        <% if current_user.fridge.title.blank? %>
          <div>
            <h1 class="text-dark mt-5 fw-bold"><%= current_user.nickname %>さんの冷蔵庫</h1><p>ID:<%= current_user.fridge_id %></p>
          </div>
        <% else %>
          <div>
            <h1 class="text-dark mt-5 fw-bold"><i class="fa-light fa-cart-shopping"></i><%= current_user.fridge.title %></h1><p>ID:<%= current_user.fridge_id %></p>
          </div>
        <% end %>

        <%# フードロス率 %>
        <% if current_user.fridge.losses.present? && current_user.fridge.shoppings.present? %>
          <h3 class="text-dark mt-5 border-bottom border-dark fw-bold">
              フードロス率
          </h3>
          
          <%# フードロス率計算 %>
          <% monthly_losses = current_user.fridge.losses.where(loss_date: Date.today.ago(1.month)..).count %>
          <% monthly_shopping_items = 0 %>
          <% current_user.fridge.shoppings.each do |shopping| %>
            <% shopping.shopping_items.each do |shopping_item| %>
              <% if Date.today.ago(1.month) < shopping_item.created_at && shopping_item.item.category_id != 5 %>
                <% monthly_shopping_items += 1 %>
              <% end %>
            <% end %>
          <% end %>
          <% monthly_losses_ratio = ((monthly_losses.to_f / monthly_shopping_items.to_f) * 100).round(2) %>

          <% three_months_losses = current_user.fridge.losses.where(loss_date: Date.today.ago(3.month)..).count %>
          <% three_months_shopping_items = 0 %>
          <% current_user.fridge.shoppings.each do |shopping| %>
            <% shopping.shopping_items.each do |shopping_item| %>
              <% if Date.today.ago(3.month) < shopping_item.created_at && shopping_item.item.category_id != 5 %>
                <% three_months_shopping_items += 1 %>
              <% end %>
            <% end %>
          <% end %>
          <% three_months_losses_ratio = ((three_months_losses.to_f / three_months_shopping_items.to_f) * 100).round(2) %>

          <% six_months_losses = current_user.fridge.losses.where(loss_date: Date.today.ago(6.months)..).count %>
          <% six_months_shopping_items = 0 %>
          <% current_user.fridge.shoppings.each do |shopping| %>
            <% shopping.shopping_items.each do |shopping_item| %>
              <% if Date.today.ago(6.months) < shopping_item.created_at && shopping_item.item.category_id != 5 %>
                <% six_months_shopping_items += 1 %>
              <% end %>
            <% end %>
          <% end %>
          <% six_months_losses_ratio = ((six_months_losses.to_f / six_months_shopping_items.to_f) * 100).round(2) %>

          <% year_losses = current_user.fridge.losses.where(loss_date: Date.today.ago(1.year)..).count %>
          <% year_shopping_items = 0 %>
          <% current_user.fridge.shoppings.each do |shopping| %>
            <% shopping.shopping_items.each do |shopping_item| %>
              <% if Date.today.ago(1.year) < shopping_item.created_at && shopping_item.item.category_id != 5 %>
                <% year_shopping_items += 1 %>
              <% end %>
            <% end %>
          <% end %>
          <% year_losses_ratio = ((year_losses.to_f / year_shopping_items.to_f) * 100).round(2) %>

          <%# プログレスバー表示 %>
          <h6 class="text-dark fw-bold mt-3">過去1ヶ月間</h6>
          <div class="progress mt-2 mb-3" style="height: 1.5rem;" >
            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= 100 - monthly_losses_ratio %>%" aria-valuenow="<%= 100 - monthly_losses_ratio %>" aria-valuemin="0" aria-valuemax="100"></div>
            <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar" style="width: <%= monthly_losses_ratio %>%" aria-valuenow="<%= monthly_losses_ratio %>" aria-valuemin="0" aria-valuemax="100">フードロス<%= monthly_losses_ratio %>%</div>
          </div>

          <button class="btn btn-outline-primary col-2 mx-auto btn-sm dropdown-toggle mt-3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseMore" aria-expanded="false" aria-controls="collapseMore">
            もっと見る
          </button>
          <div class="collapse" id="collapseMore">
            <div class="card card-body">
              <h6 class="text-dark fw-bold mt-3">過去3ヶ月間</h6>
              <div class="progress mt-2 mb-3 " style="height: 1.5rem;" >
                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= 100 - three_months_losses_ratio %>%" aria-valuenow="<%= 100 - three_months_losses_ratio %>" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar" style="width: <%= three_months_losses_ratio %>%" aria-valuenow="<%= three_months_losses_ratio %>" aria-valuemin="0" aria-valuemax="100">フードロス<%= three_months_losses_ratio %>%</div>
              </div>
              <h6 class="text-dark fw-bold mt-3">過去6ヶ月間</h6>
              <div class="progress mt-2 mb-3 " style="height: 1.5rem;" >
                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= 100 - six_months_losses_ratio %>%" aria-valuenow="<%= 100 - six_months_losses_ratio %>" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar" style="width: <%= six_months_losses_ratio %>%" aria-valuenow="<%= six_months_losses_ratio %>" aria-valuemin="0" aria-valuemax="100">フードロス<%= six_months_losses_ratio %>%</div>
              </div>
              <h6 class="text-dark fw-bold mt-3">過去1年間</h6>
              <div class="progress mt-2 mb-3 " style="height: 1.5rem;" >
                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= 100 - year_losses_ratio %>%" aria-valuenow="<%= 100 - year_losses_ratio %>" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar" style="width: <%= year_losses_ratio %>%" aria-valuenow="<%= year_losses_ratio %>" aria-valuemin="0" aria-valuemax="100">フードロス<%= year_losses_ratio %>%</div>
              </div>
            </div>
          </div>
        <% end %>
        
        <%# 新規アイテム登録フォーム %>
        <h3 class="text-dark mt-5 border-bottom border-dark fw-bold">
            アイテム登録
        </h3>

        <%= form_with model: @item, local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

          <table class="table table-hover table-sm table-borderless text-dark mt-2 ">
            <thead>
              <tr>
                <th scope="col">常備</th>
                <th scope="col">アイテム名</th>
                <th scope="col">残量</th>
                <th scope="col">カテゴリ</th>
                <th scope="col">賞味/消費期限</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.check_box :regular, {checked: true, class: "form-check-input", type: "checkbox", id: "checkboxNoLabel" }, "1", "0" %></td>
                <td><%= f.text_field :name, placeholder: "アイテム名を入力してください", class: 'form-control' %></td>
                <td><%= f.collection_select(:amount_id, Amount.all, :id, :name, {}, {class:"form-control"}) %></td>
                <td><%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form-control"}) %></td>
                <td><%= f.date_field :exp_date, class: 'form-control'%></td>
                <td><%= f.submit "登録", class: 'btn btn-primary' %></td>
            </tbody>
          </table>
        <% end %>

        <%# アイテム編集フォーム %>
        <div>
          <h3 class="text-dark mt-5 border-bottom border-dark fw-bold">
            アイテム一覧
          </h3>
        </div>
        <table class="table table-hover table-sm text-dark mt-2 mb-5">
        <thead>
          <tr>
            <th scope="col"><%= sort_link(@q, :regular, "常備" )%></th>
            <th scope="col"><%= sort_link(@q, :name, "アイテム名" )%></th>
            <th scope="col"><%= sort_link(@q, :amount_id, "残量" )%></th>
            <th scope="col"><%= sort_link(@q, :category_id, "カテゴリ" )%></th>
            <th scope="col"><%= sort_link(@q, :exp_date, "賞味/消費期限" )%></th>
            <th scope="col">最終購入日</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <% @items.each do |item| %>
          <%= render partial: "item", locals: { item: item } %>
        <% end %>
        </table>
      <% end %>
    </div>
  </div>
</div>