config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "fridges#index"
  resources :fridges, only: [:index, :create] do
    resources :shoppings, only: [:index, :create]
  end
  resources :items, only: [:create, :update, :destroy]
  resources :requests, only: [:create, :update, :destroy]
  resources :losses, only: :create
end

app/models/shopping.rb
class Shopping < ApplicationRecord
  belongs_to :fridge
  belongs_to :user
  has_many :shopping_items
  has_many :items, through: :shopping_items
end

app/models/shopping_form.rb
class ShoppingForm
  include ActiveModel::Model
  attr_accessor :shopping_date, :fridge_id, :user_id, :shopping_item_ids

  with_options presence: true do
    validates :shopping_date
    validates :fridge_id
    validates :user_id
    validates :shopping_item_ids
  end

  def save
    ids = shopping_item_ids
    Shopping.create(shopping_date: shopping_date, fridge_id: fridge_id, user_id: user_id, item_ids: ids)
    Item.where(id: ids).update_all(amount_id: 4, exp_date: nil)
  end
end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_items, only: [:index, :create]
  before_action :set_fridge, only: [:index, :create]
  before_action :same_fridge?, only: [:index, :create]

  def index
    @shopping_form = ShoppingForm.new
  end

  def create
    @shopping_form = ShoppingForm.new(shopping_params)
    if @shopping_form.valid?
      @shopping_form.save
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def shopping_params
    params.require(:shopping_form).permit(:shopping_date, shopping_item_ids: []).merge(fridge_id: params[:fridge_id],
                                                                                       user_id: current_user.id)
  end

  def set_items
    @items = Item.order('amount_id asc', 'category_id asc', 'regular desc', 'exp_date asc')
  end

  def set_fridge
    @fridge = Fridge.find(params[:fridge_id])
  end

  def same_fridge?
    redirect_to root_path unless current_user.fridge_id == Fridge.find(params[:fridge_id]).id
  end
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/shoppings/index.html.erb
<%= render "shared/header"%>
<div class= "background">
  <div class= "box">
    <div class= "container">
      <div class= "row">
        <%= form_with model: @shopping_form, url: fridge_shoppings_path, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          <h5 class="text-dark mt-5 fw-bold">
            <%= f.label :shopping_date, 'お買い物の日付を選択' %>
          </h5>
          <div class='col-3 mx-auto'>
            <%= f.date_field :shopping_date, value: Date.today, class: 'form-control' %>
          </div>
          <h3 class="text-dark mt-5 fw-bold">
            🛒 お買い物リスト 
          </h3>
          <table class="table table-hover table-light  table-sm mt-3">
            <thead>
              <tr>
                <th scope="col">購入</th>
                <th scope="col">アイテム名</th>
                <th scope="col">残量</th>
                <th scope="col">カテゴリ</th>
                <th scope="col">賞味/消費期限</th>
                <th scope="col">最終購入日</th>
              </tr>
            </thead>
            <% @items.each do |item| %>
              <tbody>
                <% if current_user.fridge_id == item.fridge_id %>
                  <tr class="table-light">
                    <td><%= f.check_box :shopping_item_ids, { multiple: true}, item.id, nil %></td>
                    <td><%= item.name %></td>
                    <td><%= item.amount.name %></td>
                    <td><%= item.category.name %></td>
                    <td><%= item.exp_date %></td>
                    <td><%= item.latest_shopping_date if item.shoppings.present? %></td>
                  </tr>
                <% else %>
                <% end %>
              </tbody>
            <% end %>
          </table>
          <%= f.submit "買い物を終了する", data: { confirm: '本当に買い物を終了しますか？'}, class: 'btn btn-warning mb-5' %>
        <% end %>
      </div>
    </div>
  </div>
</div>